# Generated by Django 4.1.3 on 2022-11-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.category'),
        ),
        migrations.AlterField(
            model_name='text',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
